version: '3.8'

services:
  app:
    build:
      context: ./app/backend
      dockerfile: docker/docker_files/Dockerfile
    restart: unless-stopped
    container_name: app
    networks:
      - inside-network
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py test
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/backend:/code
    ports:
      - 8000:8000
    env_file:
      - .env

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    networks:
      - inside-network
    env_file:
      - .env
    command: "listen --api-key ${STRIPE_SECRET} --device-name 'local' --forward-to app:8000/stripe-webhooks/"


networks:
    inside-network:
        driver: bridge